[tools]
go = "latest"
node = "latest"
"npm:eslint" = "latest"
"npm:prettier" = "latest"
"npm:typescript" = "latest"
pnpm = "latest"
python = "latest"

[env]
_.python.venv = { path = ".venv", create = true, uv_create_args = ['--seed'] } # this may need to go into the project directory, not globally
