# wallust config
# Usage: wallust run <image>

backend = "wal"
color_space = "labmixed"
palette = "harddark16"

[templates]
hyprland = { template = 'hyprland-colors.conf', target = '~/.config/hypr/colors.conf' }
waybar = { template = 'waybar-colors.css', target = '~/.config/waybar/colors.css' }
yazi = { template = 'yazi-flavor.toml', target = '~/.config/yazi/flavors/wal.yazi/flavor.toml' }
omp = { template = 'oh-my-posh.json.j2', target = '~/.config/oh-my-posh/illusi0n-box.omp.json' }
wezterm = { template = 'colorscheme.lua', target = '~/.config/wezterm/colorscheme.lua' }
wallust = { template = 'colors.json', target = '~/.config/wallust/colors.json' }
opencode = { template = 'opencode-adaptive.json', target = '~/.config/opencode/themes/adaptive.json' }
rofi = { template = 'rofi-colors.rasi', target = '~/.config/rofi/colors.rasi' }
nvim = { template = 'nvim-colorscheme.lua', target = '~/.config/nvim/colors/adaptive.lua' }
